version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: DockerfileWebApi
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    ports:
      - "5000:80"
    depends_on:
      - redis_server
  worker:
    build:
      dockerfile: DockerfileCelery
      context: .
    environment:
      REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
      WEAVIATE_HOST_PORT: ${WEAVIATE_HOST_PORT}
      WEAVIATE_GPC_URL: ${WEAVIATE_GPC_URL}
      WEAVIATE_GPC_URL_PORT: ${WEAVIATE_GPC_URL_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis_server
      
  redis_server:
    image: redis

  flower:
    image: mher/flower
    command: ["celery", "--broker=redis://redis_server:6379", "flower", "--port=5555"]
    environment:
      CE_ACCEPT_CONTENT: "json,pickle,application/json,application/json,application/x-python-serialize"
    ports:
      - "5555:5555"
    depends_on:
      - redis_server
